// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QCEServices.Infrastructure.DataAccess.Contexts;

#nullable disable

namespace QCEServices.Infrastructure.DataAccess.Migrations
{
    [DbContext(typeof(QCEServicesDbContext))]
    [Migration("20260317081420_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QCEServices.Domain.Entities.ApplicationForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Type", "Status")
                        .IsUnique();

                    b.ToTable("ApplicationForms");
                });

            modelBuilder.Entity("QCEServices.Domain.Entities.MarriageLicense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationFormId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationFormId")
                        .IsUnique();

                    b.ToTable("MarriageLicenses");
                });

            modelBuilder.Entity("QCEServices.Domain.Entities.MarriageLicense", b =>
                {
                    b.HasOne("QCEServices.Domain.Entities.ApplicationForm", "ApplicationForm")
                        .WithMany()
                        .HasForeignKey("ApplicationFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("QCEServices.Domain.Entities.Party", "Bride", b1 =>
                        {
                            b1.Property<Guid>("MarriageLicenseId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Citizenship")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("CivilStatus")
                                .HasColumnType("int");

                            b1.Property<DateOnly>("DateOfBirth")
                                .HasColumnType("date");

                            b1.Property<string>("Religion")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("MarriageLicenseId");

                            b1.ToTable("MarriageLicenses");

                            b1.WithOwner()
                                .HasForeignKey("MarriageLicenseId");

                            b1.OwnsOne("QCEServices.Domain.Entities.Place", "BirthPlace", b2 =>
                                {
                                    b2.Property<Guid>("PartyMarriageLicenseId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("CityOrMunicipality")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Country")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("ProvinceOrState")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("PartyMarriageLicenseId");

                                    b2.ToTable("MarriageLicenses");

                                    b2.WithOwner()
                                        .HasForeignKey("PartyMarriageLicenseId");
                                });

                            b1.OwnsOne("QCEServices.Domain.Entities.Person", "Name", b2 =>
                                {
                                    b2.Property<Guid>("PartyMarriageLicenseId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("FirstName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("LastName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("MiddleName")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("PartyMarriageLicenseId");

                                    b2.ToTable("MarriageLicenses");

                                    b2.WithOwner()
                                        .HasForeignKey("PartyMarriageLicenseId");
                                });

                            b1.OwnsOne("QCEServices.Domain.Entities.Parents", "Parents", b2 =>
                                {
                                    b2.Property<Guid>("PartyMarriageLicenseId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.HasKey("PartyMarriageLicenseId");

                                    b2.ToTable("MarriageLicenses");

                                    b2.WithOwner()
                                        .HasForeignKey("PartyMarriageLicenseId");

                                    b2.OwnsOne("QCEServices.Domain.Entities.Parent", "Father", b3 =>
                                        {
                                            b3.Property<Guid>("ParentsPartyMarriageLicenseId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<string>("Citizenship")
                                                .IsRequired()
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<int>("Status")
                                                .HasColumnType("int");

                                            b3.HasKey("ParentsPartyMarriageLicenseId");

                                            b3.ToTable("MarriageLicenses");

                                            b3.WithOwner()
                                                .HasForeignKey("ParentsPartyMarriageLicenseId");

                                            b3.OwnsOne("QCEServices.Domain.Entities.Person", "Name", b4 =>
                                                {
                                                    b4.Property<Guid>("ParentsPartyMarriageLicenseId")
                                                        .HasColumnType("uniqueidentifier");

                                                    b4.Property<string>("FirstName")
                                                        .IsRequired()
                                                        .HasColumnType("nvarchar(max)");

                                                    b4.Property<string>("LastName")
                                                        .IsRequired()
                                                        .HasColumnType("nvarchar(max)");

                                                    b4.Property<string>("MiddleName")
                                                        .HasColumnType("nvarchar(max)");

                                                    b4.HasKey("ParentsPartyMarriageLicenseId");

                                                    b4.ToTable("MarriageLicenses");

                                                    b4.WithOwner()
                                                        .HasForeignKey("ParentsPartyMarriageLicenseId");
                                                });

                                            b3.OwnsOne("QCEServices.Domain.Entities.Address", "Residence", b4 =>
                                                {
                                                    b4.Property<Guid>("ParentsPartyMarriageLicenseId")
                                                        .HasColumnType("uniqueidentifier");

                                                    b4.Property<string>("Barangay")
                                                        .IsRequired()
                                                        .HasColumnType("nvarchar(max)");

                                                    b4.Property<string>("CityOrMunicipality")
                                                        .IsRequired()
                                                        .HasColumnType("nvarchar(max)");

                                                    b4.Property<string>("Country")
                                                        .IsRequired()
                                                        .HasColumnType("nvarchar(max)");

                                                    b4.Property<string>("HouseNoOrStreet")
                                                        .HasColumnType("nvarchar(max)");

                                                    b4.Property<string>("ProvinceOrState")
                                                        .IsRequired()
                                                        .HasColumnType("nvarchar(max)");

                                                    b4.HasKey("ParentsPartyMarriageLicenseId");

                                                    b4.ToTable("MarriageLicenses");

                                                    b4.WithOwner()
                                                        .HasForeignKey("ParentsPartyMarriageLicenseId");
                                                });

                                            b3.Navigation("Name")
                                                .IsRequired();

                                            b3.Navigation("Residence");
                                        });

                                    b2.OwnsOne("QCEServices.Domain.Entities.Parent", "Mother", b3 =>
                                        {
                                            b3.Property<Guid>("ParentsPartyMarriageLicenseId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<string>("Citizenship")
                                                .IsRequired()
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<int>("Status")
                                                .HasColumnType("int");

                                            b3.HasKey("ParentsPartyMarriageLicenseId");

                                            b3.ToTable("MarriageLicenses");

                                            b3.WithOwner()
                                                .HasForeignKey("ParentsPartyMarriageLicenseId");

                                            b3.OwnsOne("QCEServices.Domain.Entities.Person", "Name", b4 =>
                                                {
                                                    b4.Property<Guid>("ParentsPartyMarriageLicenseId")
                                                        .HasColumnType("uniqueidentifier");

                                                    b4.Property<string>("FirstName")
                                                        .IsRequired()
                                                        .HasColumnType("nvarchar(max)");

                                                    b4.Property<string>("LastName")
                                                        .IsRequired()
                                                        .HasColumnType("nvarchar(max)");

                                                    b4.Property<string>("MiddleName")
                                                        .HasColumnType("nvarchar(max)");

                                                    b4.HasKey("ParentsPartyMarriageLicenseId");

                                                    b4.ToTable("MarriageLicenses");

                                                    b4.WithOwner()
                                                        .HasForeignKey("ParentsPartyMarriageLicenseId");
                                                });

                                            b3.OwnsOne("QCEServices.Domain.Entities.Address", "Residence", b4 =>
                                                {
                                                    b4.Property<Guid>("ParentsPartyMarriageLicenseId")
                                                        .HasColumnType("uniqueidentifier");

                                                    b4.Property<string>("Barangay")
                                                        .IsRequired()
                                                        .HasColumnType("nvarchar(max)");

                                                    b4.Property<string>("CityOrMunicipality")
                                                        .IsRequired()
                                                        .HasColumnType("nvarchar(max)");

                                                    b4.Property<string>("Country")
                                                        .IsRequired()
                                                        .HasColumnType("nvarchar(max)");

                                                    b4.Property<string>("HouseNoOrStreet")
                                                        .HasColumnType("nvarchar(max)");

                                                    b4.Property<string>("ProvinceOrState")
                                                        .IsRequired()
                                                        .HasColumnType("nvarchar(max)");

                                                    b4.HasKey("ParentsPartyMarriageLicenseId");

                                                    b4.ToTable("MarriageLicenses");

                                                    b4.WithOwner()
                                                        .HasForeignKey("ParentsPartyMarriageLicenseId");
                                                });

                                            b3.Navigation("Name")
                                                .IsRequired();

                                            b3.Navigation("Residence");
                                        });

                                    b2.Navigation("Father")
                                        .IsRequired();

                                    b2.Navigation("Mother")
                                        .IsRequired();
                                });

                            b1.OwnsOne("QCEServices.Domain.Entities.Address", "Residence", b2 =>
                                {
                                    b2.Property<Guid>("PartyMarriageLicenseId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Barangay")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("CityOrMunicipality")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Country")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("HouseNoOrStreet")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("ProvinceOrState")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("PartyMarriageLicenseId");

                                    b2.ToTable("MarriageLicenses");

                                    b2.WithOwner()
                                        .HasForeignKey("PartyMarriageLicenseId");
                                });

                            b1.Navigation("BirthPlace")
                                .IsRequired();

                            b1.Navigation("Name")
                                .IsRequired();

                            b1.Navigation("Parents")
                                .IsRequired();

                            b1.Navigation("Residence")
                                .IsRequired();
                        });

                    b.OwnsOne("QCEServices.Domain.Entities.Party", "Groom", b1 =>
                        {
                            b1.Property<Guid>("MarriageLicenseId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Citizenship")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("CivilStatus")
                                .HasColumnType("int");

                            b1.Property<DateOnly>("DateOfBirth")
                                .HasColumnType("date");

                            b1.Property<string>("Religion")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("MarriageLicenseId");

                            b1.ToTable("MarriageLicenses");

                            b1.WithOwner()
                                .HasForeignKey("MarriageLicenseId");

                            b1.OwnsOne("QCEServices.Domain.Entities.Place", "BirthPlace", b2 =>
                                {
                                    b2.Property<Guid>("PartyMarriageLicenseId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("CityOrMunicipality")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Country")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("ProvinceOrState")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("PartyMarriageLicenseId");

                                    b2.ToTable("MarriageLicenses");

                                    b2.WithOwner()
                                        .HasForeignKey("PartyMarriageLicenseId");
                                });

                            b1.OwnsOne("QCEServices.Domain.Entities.Person", "Name", b2 =>
                                {
                                    b2.Property<Guid>("PartyMarriageLicenseId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("FirstName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("LastName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("MiddleName")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("PartyMarriageLicenseId");

                                    b2.ToTable("MarriageLicenses");

                                    b2.WithOwner()
                                        .HasForeignKey("PartyMarriageLicenseId");
                                });

                            b1.OwnsOne("QCEServices.Domain.Entities.Parents", "Parents", b2 =>
                                {
                                    b2.Property<Guid>("PartyMarriageLicenseId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.HasKey("PartyMarriageLicenseId");

                                    b2.ToTable("MarriageLicenses");

                                    b2.WithOwner()
                                        .HasForeignKey("PartyMarriageLicenseId");

                                    b2.OwnsOne("QCEServices.Domain.Entities.Parent", "Father", b3 =>
                                        {
                                            b3.Property<Guid>("ParentsPartyMarriageLicenseId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<string>("Citizenship")
                                                .IsRequired()
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<int>("Status")
                                                .HasColumnType("int");

                                            b3.HasKey("ParentsPartyMarriageLicenseId");

                                            b3.ToTable("MarriageLicenses");

                                            b3.WithOwner()
                                                .HasForeignKey("ParentsPartyMarriageLicenseId");

                                            b3.OwnsOne("QCEServices.Domain.Entities.Person", "Name", b4 =>
                                                {
                                                    b4.Property<Guid>("ParentsPartyMarriageLicenseId")
                                                        .HasColumnType("uniqueidentifier");

                                                    b4.Property<string>("FirstName")
                                                        .IsRequired()
                                                        .HasColumnType("nvarchar(max)");

                                                    b4.Property<string>("LastName")
                                                        .IsRequired()
                                                        .HasColumnType("nvarchar(max)");

                                                    b4.Property<string>("MiddleName")
                                                        .HasColumnType("nvarchar(max)");

                                                    b4.HasKey("ParentsPartyMarriageLicenseId");

                                                    b4.ToTable("MarriageLicenses");

                                                    b4.WithOwner()
                                                        .HasForeignKey("ParentsPartyMarriageLicenseId");
                                                });

                                            b3.OwnsOne("QCEServices.Domain.Entities.Address", "Residence", b4 =>
                                                {
                                                    b4.Property<Guid>("ParentsPartyMarriageLicenseId")
                                                        .HasColumnType("uniqueidentifier");

                                                    b4.Property<string>("Barangay")
                                                        .IsRequired()
                                                        .HasColumnType("nvarchar(max)");

                                                    b4.Property<string>("CityOrMunicipality")
                                                        .IsRequired()
                                                        .HasColumnType("nvarchar(max)");

                                                    b4.Property<string>("Country")
                                                        .IsRequired()
                                                        .HasColumnType("nvarchar(max)");

                                                    b4.Property<string>("HouseNoOrStreet")
                                                        .HasColumnType("nvarchar(max)");

                                                    b4.Property<string>("ProvinceOrState")
                                                        .IsRequired()
                                                        .HasColumnType("nvarchar(max)");

                                                    b4.HasKey("ParentsPartyMarriageLicenseId");

                                                    b4.ToTable("MarriageLicenses");

                                                    b4.WithOwner()
                                                        .HasForeignKey("ParentsPartyMarriageLicenseId");
                                                });

                                            b3.Navigation("Name")
                                                .IsRequired();

                                            b3.Navigation("Residence");
                                        });

                                    b2.OwnsOne("QCEServices.Domain.Entities.Parent", "Mother", b3 =>
                                        {
                                            b3.Property<Guid>("ParentsPartyMarriageLicenseId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<string>("Citizenship")
                                                .IsRequired()
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<int>("Status")
                                                .HasColumnType("int");

                                            b3.HasKey("ParentsPartyMarriageLicenseId");

                                            b3.ToTable("MarriageLicenses");

                                            b3.WithOwner()
                                                .HasForeignKey("ParentsPartyMarriageLicenseId");

                                            b3.OwnsOne("QCEServices.Domain.Entities.Person", "Name", b4 =>
                                                {
                                                    b4.Property<Guid>("ParentsPartyMarriageLicenseId")
                                                        .HasColumnType("uniqueidentifier");

                                                    b4.Property<string>("FirstName")
                                                        .IsRequired()
                                                        .HasColumnType("nvarchar(max)");

                                                    b4.Property<string>("LastName")
                                                        .IsRequired()
                                                        .HasColumnType("nvarchar(max)");

                                                    b4.Property<string>("MiddleName")
                                                        .HasColumnType("nvarchar(max)");

                                                    b4.HasKey("ParentsPartyMarriageLicenseId");

                                                    b4.ToTable("MarriageLicenses");

                                                    b4.WithOwner()
                                                        .HasForeignKey("ParentsPartyMarriageLicenseId");
                                                });

                                            b3.OwnsOne("QCEServices.Domain.Entities.Address", "Residence", b4 =>
                                                {
                                                    b4.Property<Guid>("ParentsPartyMarriageLicenseId")
                                                        .HasColumnType("uniqueidentifier");

                                                    b4.Property<string>("Barangay")
                                                        .IsRequired()
                                                        .HasColumnType("nvarchar(max)");

                                                    b4.Property<string>("CityOrMunicipality")
                                                        .IsRequired()
                                                        .HasColumnType("nvarchar(max)");

                                                    b4.Property<string>("Country")
                                                        .IsRequired()
                                                        .HasColumnType("nvarchar(max)");

                                                    b4.Property<string>("HouseNoOrStreet")
                                                        .HasColumnType("nvarchar(max)");

                                                    b4.Property<string>("ProvinceOrState")
                                                        .IsRequired()
                                                        .HasColumnType("nvarchar(max)");

                                                    b4.HasKey("ParentsPartyMarriageLicenseId");

                                                    b4.ToTable("MarriageLicenses");

                                                    b4.WithOwner()
                                                        .HasForeignKey("ParentsPartyMarriageLicenseId");
                                                });

                                            b3.Navigation("Name")
                                                .IsRequired();

                                            b3.Navigation("Residence");
                                        });

                                    b2.Navigation("Father")
                                        .IsRequired();

                                    b2.Navigation("Mother")
                                        .IsRequired();
                                });

                            b1.OwnsOne("QCEServices.Domain.Entities.Address", "Residence", b2 =>
                                {
                                    b2.Property<Guid>("PartyMarriageLicenseId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Barangay")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("CityOrMunicipality")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Country")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("HouseNoOrStreet")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("ProvinceOrState")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("PartyMarriageLicenseId");

                                    b2.ToTable("MarriageLicenses");

                                    b2.WithOwner()
                                        .HasForeignKey("PartyMarriageLicenseId");
                                });

                            b1.Navigation("BirthPlace")
                                .IsRequired();

                            b1.Navigation("Name")
                                .IsRequired();

                            b1.Navigation("Parents")
                                .IsRequired();

                            b1.Navigation("Residence")
                                .IsRequired();
                        });

                    b.Navigation("ApplicationForm");

                    b.Navigation("Bride")
                        .IsRequired();

                    b.Navigation("Groom")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
